### ISSUE TITLE
SOLVED - Tutorial not Working

### ISSUE THREAD

**Issue by Gabrock94** [curiositry/EEGrunt#10]
Hi, 
The tutorial at  http://www.autodidacts.io/analyze-ecg-heart-rate-and-hrv-with-python-and-eegrunt/ is not working. A fix to the readme file or to the blog is needed. 

Hope this help :)

**Comment by curiositry** [comment]
Can you provide any more details about what’s not working @Gabrock94? Are there error messages in the console when you run the script?

**Comment by Gabrock94** [comment]
Solved, the website was just temporary down. Thanks

**Comment by curiositry** [comment]
Ah, yes. Autodidacts.io had some unexpected downtime today — my fault :disappointed:

**Comment by Gabrock94** [comment]
Don't mind :) Thank you so much for your help :)
