### ISSUE TITLE
EEG.data = EEG.bandpass(start,stop)

### ISSUE THREAD

**Issue by Dibbledeedoo** [curiositry/EEGrunt#11]
There is no mention of this line from analyze_data.py in the Getting Started section, but it appears that the start/stop variables must be set in order to run the program. Am I missing something? Otherwise, what should those be set to? Thanks for your assistance.

**Comment by curiositry** [comment]
@Dibbledeedoo Good point. That line should be commented out by default. 

The bandpass function takes the data and applies a butterworth bandpass filter. The `start` and `stop` arguments set the frequency range to bandpass, in Hertz. But it’s optional: most of the time it’s not used, and it shouldn’t stop the program from running.

**Comment by curiositry** [comment]
@Dibbledeedoo This has been fixed in 9bd55307eaaee667db4da9ad6a47d41d405b1af9.
