### ISSUE TITLE
Is the OpenBCI ganglion board supported?

### ISSUE THREAD

**Issue by digitalgutenberg** [curiositry/EEGrunt#15]
Hi there, great program!

I have some raw OpenBCI recordings that I’m not able to analyze. The OpenBCI board in question is the Ganglion, the recording (txt) is conducted using the OpenBCI gui. I’m able to analyze the raw sample (eegrunt-obci-raw-test-data.txt) that comes with EEGrunt, but my recording won’t run. The source is set to 'openbci' in analyze_data.py.

> digitalgutenberg@soap ~/git/EEGrunt $ python analyze_data.py
> Loading EEG data: data/OpenBCI-RAW-2017-03-12_22-40-25.txt
> Traceback (most recent call last):
>   File "analyze_data.py", line 29, in <module>
>     EEG.load_data()
>   File "/home/digitalgutenberg/git/EEGrunt/EEGrunt.py", line 78, in load_data
>     usecols=(0,1,2,3,4,5,6,7,8)
>   File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 923, in loadtxt
>     vals = [vals[i] for i in usecols]
> IndexError: list index out of range

So, is this simply because EEGrunt doesn’t support the Ganglion, or is there some kind of user error on my end? I've used the default settings.

EEG recording:
https://github.com/digitalgutenberg/EEG-recordings/blob/master/OpenBCI-RAW-2017-03-12_22-40-25.txt
 
Thanks in advance!

**Comment by curiositry** [comment]
As far as I’m aware the recording format is the same, so it should support the Ganglion data without any issues. I’ll take a look and get back to you :)

**Comment by curiositry** [comment]
Hi again @digitalgutenberg. I think I’ve sorted out the problem: The Ganglion data includes six commented out lines at the beginning, rather than five, so it was having issues with that, and we neglected to add a preset for the Ganglion, so you’ll need to manually adjust the channel count for the time being. 

Open EEGrunt.py and change lines 22–23 to:
```python
self.nchannels = 4
self.channels = [1,2,3,4]
```

Line 74 to:
```python 
skiprows = 6
```

And line 78 to:

```python
usecols=(0,1,2,3,4)
```

And you should be ready to go!

I’ll add a proper preset for the Ganglion shortly, so you don’t have to go and edit `EEGrunt.py` manually. 

Thanks for noticing this!

**Comment by digitalgutenberg** [comment]
Awesome, works perfectly, thanks a lot!

By the way, since the Ganglion apparently records at 200hz, I suppose I should change `self.fs_Hz` and
`self.NFFT` too? 200 and 200*2?

**Comment by curiositry** [comment]
Yeah, the sample rate too :/

**Comment by curiositry** [comment]
@digitalgutenberg As of 9ed2b46b5745d5b749be044a8834d884f74fedd1, I have added a preset for working with OpenBCI Ganglion data. Let me know if you have any feedback or discover any bugs :)

(Note: I didn’t have any Ganglion OpenViBE data on hand, so the 'openbci-ganglion-openvibe' source is still untested.)
