### ISSUE TITLE
Indices

### ISSUE THREAD

**Issue by Era498** [curiositry/EEGrunt#16]
Hello!

I've been trying to get this program to run on my computer, but have been encountering issues when I run analyze_data.py.

I'm pretty new to linux and python, so it's possible I installed something incorrectly/am doing something horribly wrong.

Dunno if its helpful, but I'm running Ubuntu and trying to get the program to run through ipython.

The first error I get is:  IndexError: too many indices for array

Referring to:
/home/user/Downloads/EEGrunt-master/EEGrunt.pyc in load_channel(self, channel)
    110     def load_channel(self,channel):
    111         print("Loading channel: "+str(channel))
--> 112         channel_data = self.raw_data[:,(channel+self.col_offset)]
    113         self.channel = channel
    114         self.data = channel_data

I googled a little bit and tried to fix the error by adding ndmin = 2 to raw_data, which changes the error to: IndexError: index 0 is out of bounds for axis 1 with size 0

Referring to: 
/home/user/Downloads/EEGrunt-master/EEGrunt.pyc in load_channel(self, channel)
    110     def load_channel(self,channel):
    111         print("Loading channel: "+str(channel))
--> 112         channel_data = self.raw_data[:,(channel+self.col_offset)]
    113         self.channel = channel
    114         self.data = channel_data

I'm pretty sure I'm just missing something, because I don't see any other references to this error.

Thanks!

**Comment by curiositry** [comment]
@Era498 What data are you running it on? Is it from the OpenBCI Ganglion board, the OpenBCI Cyton, or the Muse? And what software did you record it with — the OpenBCI GUI, OpenViBE, or the Muse app?

Knowing this info will help me troubleshoot.

**Comment by Era498** [comment]
@curiositry, It's a muse, and because it's a muse 2016, I recorded it with a python program I found on here called muse-lsl (https://github.com/alexandrebarachant/muse-lsl/blob/master/muse-record.py)

**Comment by curiositry** [comment]
@Era498 Aha. The LSL data format is quite different Muse’s data format, which is why you were running into that error. 

I looked at the recordings in Alexandre’s repository for reference and added a preset for Muse LSL data in 63937d45b5d4f16699fd455a7fe1eecfe0bb13e4.

If you get the new version of EEGrunt.py and set the `source` variable to `muse-lsl`, you should be good to go :smile:

**Comment by Era498** [comment]
@curiositry Wow thanks!

**Comment by curiositry** [comment]
De nada :)
