### ISSUE TITLE
Installation on Mac OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by niedfelj** [curiositry/EEGrunt#9]
I just got this to run on mac os x 10.11 doing the following (you need homebrew installed):

```
brew install python
pip install numpy
pip install scipy
pip install matplotlib
```

It appeared to hang after generating the spectrogram.

```
Joels-iMac:EEGrunt joel$ python analyze_data.py 
Loading EEG data: data/eegrunt-obci-ovibe-test-data.csv
Loading channel: 1
Processing channel 1
Highpass filtering at: 1.0 Hz
Notch filter removing: 57.0-63.0 Hz
Generating signal plot...
Calculating spectrum data...
Generating spectrogram...
^CTraceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1889, in button_press_event
    def button_press_event(self, x, y, button, dblclick=False, guiEvent=None):
KeyboardInterrupt
^C^C^C^C^C^C
^D
```

<img width="798" alt="screen shot 2015-11-24 at 3 56 19 pm" src="https://cloud.githubusercontent.com/assets/294487/11380424/f017971e-92c3-11e5-9d9f-b8b98af83d9a.png">

**Comment by niedfelj** [comment]
Actually, it seems like it waits for me to close each graph/plot before continuing?

**Comment by curiositry** [comment]
@niedfelj Yes, at the moment if the plot is set to show, it waits to process the next one until the first is closed. If you set it to save the plots to a directory (a matter of changing `EEG.plot = 'show'`  to `EEG.plot = 'save'` in `analyze_data.py`) then it will do them all. This isn’t ideal, though. I’ll look into a better solution as soon as I get a chance :)

(Nice to see you have it running on Mac! I should add a script to install dependencies on OSX…)

**Comment by curiositry** [comment]
This should be resolved, now that the showplots function is called post-analysis.
